// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Attachment           string                 `protobuf:"bytes,4,opt,name=attachment,proto3" json:"attachment,omitempty"`
	AttributedTo         string                 `protobuf:"bytes,5,opt,name=attributedTo,proto3" json:"attributedTo,omitempty"`
	Context              string                 `protobuf:"bytes,8,opt,name=context,proto3" json:"context,omitempty"`
	MediaType            string                 `protobuf:"bytes,9,opt,name=mediaType,proto3" json:"mediaType,omitempty"`
	EndTime              *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Generator            string                 `protobuf:"bytes,11,opt,name=generator,proto3" json:"generator,omitempty"`
	Icon                 string                 `protobuf:"bytes,12,opt,name=icon,proto3" json:"icon,omitempty"`
	Image                string                 `protobuf:"bytes,13,opt,name=image,proto3" json:"image,omitempty"`
	InReplyTo            string                 `protobuf:"bytes,14,opt,name=inReplyTo,proto3" json:"inReplyTo,omitempty"`
	Location             string                 `protobuf:"bytes,15,opt,name=location,proto3" json:"location,omitempty"`
	Preview              string                 `protobuf:"bytes,16,opt,name=preview,proto3" json:"preview,omitempty"`
	Published            *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=published,proto3" json:"published,omitempty"`
	Replies              string                 `protobuf:"bytes,18,opt,name=replies,proto3" json:"replies,omitempty"`
	StartTime            *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=startTime,proto3" json:"startTime,omitempty"`
	Summary              string                 `protobuf:"bytes,20,opt,name=summary,proto3" json:"summary,omitempty"`
	Tag                  []string               `protobuf:"bytes,21,rep,name=tag,proto3" json:"tag,omitempty"`
	Updated              *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=updated,proto3" json:"updated,omitempty"`
	Url                  string                 `protobuf:"bytes,23,opt,name=url,proto3" json:"url,omitempty"`
	To                   []string               `protobuf:"bytes,24,rep,name=to,proto3" json:"to,omitempty"`
	Bto                  []string               `protobuf:"bytes,25,rep,name=bto,proto3" json:"bto,omitempty"`
	Cc                   []string               `protobuf:"bytes,26,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc                  []string               `protobuf:"bytes,27,rep,name=bcc,proto3" json:"bcc,omitempty"`
	Likes                string                 `protobuf:"bytes,29,opt,name=likes,proto3" json:"likes,omitempty"`
	Shares               string                 `protobuf:"bytes,30,opt,name=shares,proto3" json:"shares,omitempty"`
	Inbox                string                 `protobuf:"bytes,32,opt,name=inbox,proto3" json:"inbox,omitempty"`
	Outbox               string                 `protobuf:"bytes,33,opt,name=outbox,proto3" json:"outbox,omitempty"`
	Following            string                 `protobuf:"bytes,34,opt,name=following,proto3" json:"following,omitempty"`
	Followers            string                 `protobuf:"bytes,35,opt,name=followers,proto3" json:"followers,omitempty"`
	Liked                string                 `protobuf:"bytes,36,opt,name=liked,proto3" json:"liked,omitempty"`
	PreferredUsername    string                 `protobuf:"bytes,37,opt,name=preferredUsername,proto3" json:"preferredUsername,omitempty"`
	Endpoints            string                 `protobuf:"bytes,38,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	Streams              []string               `protobuf:"bytes,39,rep,name=streams,proto3" json:"streams,omitempty"`
	PublicKey            string                 `protobuf:"bytes,40,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Person) GetAttachment() string {
	if m != nil {
		return m.Attachment
	}
	return ""
}

func (m *Person) GetAttributedTo() string {
	if m != nil {
		return m.AttributedTo
	}
	return ""
}

func (m *Person) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *Person) GetMediaType() string {
	if m != nil {
		return m.MediaType
	}
	return ""
}

func (m *Person) GetEndTime() *timestamppb.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *Person) GetGenerator() string {
	if m != nil {
		return m.Generator
	}
	return ""
}

func (m *Person) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Person) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Person) GetInReplyTo() string {
	if m != nil {
		return m.InReplyTo
	}
	return ""
}

func (m *Person) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Person) GetPreview() string {
	if m != nil {
		return m.Preview
	}
	return ""
}

func (m *Person) GetPublished() *timestamppb.Timestamp {
	if m != nil {
		return m.Published
	}
	return nil
}

func (m *Person) GetReplies() string {
	if m != nil {
		return m.Replies
	}
	return ""
}

func (m *Person) GetStartTime() *timestamppb.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Person) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *Person) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *Person) GetUpdated() *timestamppb.Timestamp {
	if m != nil {
		return m.Updated
	}
	return nil
}

func (m *Person) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Person) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Person) GetBto() []string {
	if m != nil {
		return m.Bto
	}
	return nil
}

func (m *Person) GetCc() []string {
	if m != nil {
		return m.Cc
	}
	return nil
}

func (m *Person) GetBcc() []string {
	if m != nil {
		return m.Bcc
	}
	return nil
}

func (m *Person) GetLikes() string {
	if m != nil {
		return m.Likes
	}
	return ""
}

func (m *Person) GetShares() string {
	if m != nil {
		return m.Shares
	}
	return ""
}

func (m *Person) GetInbox() string {
	if m != nil {
		return m.Inbox
	}
	return ""
}

func (m *Person) GetOutbox() string {
	if m != nil {
		return m.Outbox
	}
	return ""
}

func (m *Person) GetFollowing() string {
	if m != nil {
		return m.Following
	}
	return ""
}

func (m *Person) GetFollowers() string {
	if m != nil {
		return m.Followers
	}
	return ""
}

func (m *Person) GetLiked() string {
	if m != nil {
		return m.Liked
	}
	return ""
}

func (m *Person) GetPreferredUsername() string {
	if m != nil {
		return m.PreferredUsername
	}
	return ""
}

func (m *Person) GetEndpoints() string {
	if m != nil {
		return m.Endpoints
	}
	return ""
}

func (m *Person) GetStreams() []string {
	if m != nil {
		return m.Streams
	}
	return nil
}

func (m *Person) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type Account struct {
	Person               *Person                `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	Password             string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email                string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Account) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

// collection of Persons
type Persons struct {
	Persons              []*Person `protobuf:"bytes,1,rep,name=Persons,proto3" json:"Persons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Persons) Reset()         { *m = Persons{} }
func (m *Persons) String() string { return proto.CompactTextString(m) }
func (*Persons) ProtoMessage()    {}
func (*Persons) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{2}
}

func (m *Persons) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Persons.Unmarshal(m, b)
}
func (m *Persons) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Persons.Marshal(b, m, deterministic)
}
func (m *Persons) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Persons.Merge(m, src)
}
func (m *Persons) XXX_Size() int {
	return xxx_messageInfo_Persons.Size(m)
}
func (m *Persons) XXX_DiscardUnknown() {
	xxx_messageInfo_Persons.DiscardUnknown(m)
}

var xxx_messageInfo_Persons proto.InternalMessageInfo

func (m *Persons) GetPersons() []*Person {
	if m != nil {
		return m.Persons
	}
	return nil
}

// collection of Accounts
type Accounts struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Accounts) Reset()         { *m = Accounts{} }
func (m *Accounts) String() string { return proto.CompactTextString(m) }
func (*Accounts) ProtoMessage()    {}
func (*Accounts) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{3}
}

func (m *Accounts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Accounts.Unmarshal(m, b)
}
func (m *Accounts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Accounts.Marshal(b, m, deterministic)
}
func (m *Accounts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Accounts.Merge(m, src)
}
func (m *Accounts) XXX_Size() int {
	return xxx_messageInfo_Accounts.Size(m)
}
func (m *Accounts) XXX_DiscardUnknown() {
	xxx_messageInfo_Accounts.DiscardUnknown(m)
}

var xxx_messageInfo_Accounts proto.InternalMessageInfo

func (m *Accounts) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "model.Person")
	proto.RegisterType((*Account)(nil), "model.Account")
	proto.RegisterType((*Persons)(nil), "model.Persons")
	proto.RegisterType((*Accounts)(nil), "model.Accounts")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 656 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0x55, 0x92, 0x36, 0x1f, 0xee, 0x07, 0xad, 0x29, 0x65, 0x08, 0x50, 0x42, 0xa0, 0x34, 0x42,
	0x28, 0x95, 0x0a, 0x42, 0x70, 0xec, 0x99, 0x0b, 0x8a, 0xc2, 0x19, 0x39, 0xde, 0x69, 0x62, 0xb1,
	0x6b, 0xaf, 0xec, 0x59, 0xda, 0xfc, 0x59, 0x7e, 0x02, 0xbf, 0x01, 0xf9, 0x63, 0x37, 0x45, 0x3d,
	0xe4, 0xe6, 0xf7, 0xe6, 0xcd, 0x5b, 0x8f, 0x67, 0x76, 0xd8, 0x7e, 0x89, 0xd6, 0x19, 0x3d, 0x2d,
	0xad, 0x21, 0xc3, 0x77, 0x0b, 0x93, 0x61, 0x3e, 0x7c, 0xb5, 0x34, 0x66, 0x99, 0xe3, 0x65, 0x20,
	0x17, 0xd5, 0xcd, 0x25, 0xa9, 0x02, 0x1d, 0x89, 0xa2, 0x8c, 0xba, 0xf1, 0x9f, 0x1e, 0xeb, 0x7e,
	0x0f, 0x89, 0xfc, 0x90, 0xb5, 0x55, 0x06, 0xad, 0x51, 0x6b, 0x32, 0x98, 0xb5, 0x55, 0xc6, 0xcf,
	0x18, 0x13, 0x44, 0x42, 0xae, 0x0a, 0xd4, 0x04, 0x3b, 0x81, 0xbf, 0xc7, 0xf0, 0x31, 0xdb, 0x17,
	0x44, 0x56, 0x2d, 0x2a, 0xc2, 0x6c, 0x6e, 0x60, 0x37, 0x28, 0xfe, 0xe3, 0x38, 0xb0, 0x9e, 0x34,
	0x9a, 0xf0, 0x8e, 0xa0, 0x1f, 0xc2, 0x35, 0xe4, 0x2f, 0xd8, 0xa0, 0xc0, 0x4c, 0x89, 0xf9, 0xba,
	0x44, 0x18, 0x84, 0xd8, 0x86, 0xe0, 0x9f, 0x58, 0x0f, 0x75, 0x36, 0x57, 0x05, 0x02, 0x1b, 0xb5,
	0x26, 0x7b, 0x57, 0xc3, 0x69, 0xac, 0x64, 0x5a, 0x57, 0x32, 0x9d, 0xd7, 0x95, 0xcc, 0x6a, 0xa9,
	0xf7, 0x5c, 0xa2, 0x46, 0x2b, 0xc8, 0x58, 0xd8, 0x8b, 0x9e, 0x0d, 0xc1, 0x39, 0xdb, 0x51, 0xd2,
	0x68, 0xd8, 0x0f, 0x81, 0x70, 0xe6, 0x27, 0x6c, 0x57, 0x15, 0x62, 0x89, 0x70, 0x10, 0xc8, 0x08,
	0xbc, 0x8f, 0xd2, 0x33, 0x2c, 0xf3, 0xf5, 0xdc, 0xc0, 0x61, 0xf4, 0x69, 0x08, 0x3e, 0x64, 0xfd,
	0xdc, 0x48, 0x41, 0xca, 0x68, 0x78, 0x14, 0x82, 0x0d, 0xf6, 0xf5, 0x96, 0x16, 0x7f, 0x2b, 0xbc,
	0x85, 0xa3, 0x58, 0x6f, 0x82, 0xfc, 0x0b, 0x1b, 0x94, 0xd5, 0x22, 0x57, 0x6e, 0x85, 0x19, 0x1c,
	0x6f, 0xad, 0x69, 0x23, 0xf6, 0x9e, 0x16, 0xcb, 0x5c, 0xa1, 0x03, 0x1e, 0x3d, 0x13, 0xf4, 0x9e,
	0x8e, 0x84, 0xa5, 0xf0, 0x4e, 0x8f, 0xb7, 0x7b, 0x36, 0x62, 0xef, 0xe9, 0xaa, 0xa2, 0x10, 0x76,
	0x0d, 0x27, 0xd1, 0x33, 0x41, 0x7e, 0xc4, 0x3a, 0x24, 0x96, 0xf0, 0x64, 0xd4, 0x99, 0x0c, 0x66,
	0xfe, 0xe8, 0x7b, 0x51, 0x95, 0x99, 0x20, 0xcc, 0xe0, 0x74, 0x7b, 0x2f, 0x92, 0xd4, 0xfb, 0x54,
	0x36, 0x87, 0xa7, 0xc1, 0xdd, 0x1f, 0xfd, 0x7c, 0x91, 0x01, 0x08, 0xc6, 0x6d, 0x32, 0x5e, 0xb1,
	0x20, 0x03, 0xcf, 0xe2, 0x97, 0x16, 0x64, 0xbc, 0x42, 0x4a, 0x18, 0x46, 0x85, 0x94, 0x41, 0x21,
	0x25, 0x3c, 0x4f, 0x0a, 0x29, 0x7d, 0xbf, 0x72, 0xf5, 0x0b, 0x1d, 0xbc, 0x8c, 0xfd, 0x0a, 0x80,
	0x9f, 0xb2, 0xae, 0x5b, 0x09, 0x8b, 0x0e, 0xce, 0x02, 0x9d, 0x50, 0xe8, 0xae, 0x5e, 0x98, 0x3b,
	0x18, 0xa5, 0xee, 0x7a, 0xe0, 0xd5, 0xa6, 0x22, 0x4f, 0xbf, 0x8e, 0xea, 0x88, 0x7c, 0xd7, 0x6f,
	0x4c, 0x9e, 0x9b, 0x5b, 0xa5, 0x97, 0x30, 0x8e, 0x5d, 0x6f, 0x88, 0x4d, 0x14, 0xad, 0x83, 0x37,
	0xf7, 0xa3, 0x68, 0x5d, 0x7d, 0xaf, 0x0c, 0xde, 0x6e, 0xee, 0x95, 0xf1, 0x0f, 0xec, 0xb8, 0xb4,
	0x78, 0x83, 0xd6, 0x62, 0xf6, 0xc3, 0xa1, 0xd5, 0xa2, 0x40, 0x38, 0x0f, 0x8a, 0x87, 0x01, 0xff,
	0x05, 0xd4, 0x59, 0x69, 0x94, 0x26, 0x07, 0xef, 0xe2, 0x17, 0x1a, 0x22, 0x74, 0x8c, 0x2c, 0x8a,
	0xc2, 0xc1, 0x45, 0x78, 0x8f, 0x1a, 0xfa, 0xbc, 0x30, 0x2c, 0xf2, 0x1b, 0xae, 0x61, 0x12, 0xf3,
	0x1a, 0x62, 0xfc, 0xb7, 0xc5, 0x7a, 0xd7, 0x52, 0x9a, 0x4a, 0x13, 0x3f, 0x67, 0xdd, 0xb8, 0x24,
	0xc2, 0x5f, 0xbe, 0x77, 0x75, 0x30, 0x0d, 0x5b, 0x62, 0x1a, 0x17, 0xc0, 0x2c, 0x05, 0xfd, 0x80,
	0x97, 0xc2, 0xb9, 0x5b, 0x63, 0x33, 0x68, 0xc7, 0x01, 0xaf, 0xb1, 0x2f, 0x14, 0x0b, 0xa1, 0x72,
	0xe8, 0xc4, 0x42, 0x03, 0xf0, 0x6c, 0xb9, 0x32, 0x1a, 0xd3, 0x96, 0x88, 0x80, 0x7f, 0x65, 0x4c,
	0x5a, 0xf4, 0xd3, 0xf0, 0x53, 0x50, 0x58, 0x0f, 0x5b, 0xe6, 0x33, 0xa9, 0xaf, 0xc9, 0xa7, 0xa6,
	0x41, 0xf2, 0xa9, 0xdd, 0xed, 0xa9, 0x49, 0x7d, 0x4d, 0xe3, 0x2b, 0xd6, 0x8b, 0xf5, 0x38, 0x7e,
	0xd1, 0x1c, 0xa1, 0x35, 0xea, 0x3c, 0x2c, 0xb8, 0x8e, 0x8e, 0x3f, 0xb3, 0x7e, 0x7a, 0x23, 0xc7,
	0xdf, 0xb3, 0xbe, 0x48, 0xe7, 0x94, 0x75, 0x98, 0xb2, 0x92, 0x64, 0xd6, 0xc4, 0x17, 0xdd, 0x70,
	0x95, 0x8f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x90, 0x59, 0x08, 0x3d, 0x7c, 0x05, 0x00, 0x00,
}
