# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install protoc
      run: |
        if ! command -v protoc &> /dev/null; then
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v25.0-rc1/protoc-25.0-rc-1-linux-x86_64.zip
          unzip protoc-25.0-rc-1-linux-x86_64.zip
          sudo mv bin/protoc /usr/local/bin
          sudo mv include/google /usr/local/include
        fi

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: |
        go mod tidy
        go mod vendor

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
